[package]
name = "panopto"
version = "0.1.0"
authors = ["Thomas Hinds <thinds101@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.63"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
